In [4]:
import pandas as pd

In [5]:
# !pip install pandas

In [6]:
pd.read_csv('DF_FAULT[alpha_4000_4046]2.csv')

,Unnamed: 0,bias,betha_1,betha_2,betha_3,betha_4,betha_5
0,count,553.000000,553.000000,553.000000,553.000000,553.000000,553.000000
1,mean,1.800102,-0.741206,-0.074096,2.698100,0.298995,-0.107350
2,std,0.594829,1.453320,0.483359,2.420349,0.436940,0.282173
3,min,1.398649,-15.400250,-4.402266,1.800498,-0.586097,-2.723942
4,25%,1.499645,-0.726607,-0.137875,2.280102,0.148490,-0.181228
5,50%,1.697465,-0.596494,0.052922,2.425391,0.230216,-0.069145
6,75%,2.089371,-0.439203,0.127526,2.567290,0.372789,0.010269
7,max,7.363404,0.375298,0.694434,26.843431,4.708123,0.427552